/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DemoToken } from "./DemoToken";
export type { DisciplinaryRegistry } from "./DisciplinaryRegistry";
export type { Lock } from "./Lock";
export type { PrizePool } from "./PrizePool";
export type { RoleManager } from "./RoleManager";
export type { SponsorshipRegistry } from "./SponsorshipRegistry";
export type { TransferRegistry } from "./TransferRegistry";
