/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DemoToken__factory } from "./DemoToken__factory";
export { DisciplinaryRegistry__factory } from "./DisciplinaryRegistry__factory";
export { Lock__factory } from "./Lock__factory";
export { PrizePool__factory } from "./PrizePool__factory";
export { RoleManager__factory } from "./RoleManager__factory";
export { SponsorshipRegistry__factory } from "./SponsorshipRegistry__factory";
export { TransferRegistry__factory } from "./TransferRegistry__factory";
